# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue in the Card Name Fit library! 👋 We'll review it as soon as possible.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  Thanks for opening your first pull request in the Card Name Fit library! 🎉 We'll review it shortly.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request to the Card Name Fit library! 🚀 Thank you for contributing! 